project_name: errgroupcheck

release:
  github:
    owner: alexbagnolini
    name: errgroupcheck

builds:
- skip: true

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^chore:'
    - '^refactor:'
    - 'README'
    - Merge pull request
    - Merge branch
